### ISSUE TITLE
Feature Request: Support File Logging

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#106]
I'm currently trying to migrate the `PactNet` library to use the Rust reference implementation via FFI and I'm encountering some problems (probably in my new interop code...). I'm getting a response saying that the request in my sample consumer test wasn't expected:

```
System.Net.Http.HttpRequestException
The Events API request for GET http://localhost:6868/events/83f9262f-28f1-4703-ab1a-8cfd9e8249c9 failed. Response Status: 
500, Response Body: {"error":"Unexpected-Request : Request { method: \"GET\", path: \"/events/83f9262f-28f1-4703-ab1a-8cfd9e8249c9\", 
query: None, headers: Some({\"authorization\": [\"Bearer abcdef1234567890\"], \"host\": [\"localhost:6868\"], \"accept\": 
[\"application/json\"], \"connection\": [\"Keep-Alive\"]}), body: Empty, matching_rules: MatchingRules { rules: {} }, generators: 
Generators { categories: {} } }"}
```

The problem is that there's no way to get any of the logging out of the Rust module because it logs to stdout/stderr and the most popular testing framework in .Net land (xUnit) doesn't capture console output (so that tests can be run in parallel without their output interleaving).

It would be very helpful if I could get the mock server to write to a file instead of the console so that it can be inspected afterwards. I'm sure if I saw the registered interactions vs. my actual request I'd spot the problem really quickly, but without knowing the interactions (from the logging) then it's incredibly difficult to track down what's gone wrong.

**Comment by mefellows** [comment]
In case it's not clear (I think it is) on the consumer side, you can extract the errors via this ffi call `mock_server_mismatches`:

See: https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_ffi/src/lib.rs#L328-L355

I was talking to @TimothyJones about this yesterday, and we were having the opposite thoughts (context is for Pact JS) - logging to a file is a pain, because CI etc.

But eventually, we'd like to print out xunit and other reporters so it will be necessary.

But one option is to do _both_ (configurable).

Also your feedback on https://github.com/pact-foundation/pact-reference/pull/105 would be interesting. We're exploring the idea of centralised logging through the rust core so we have a central event log for debugging etc.

**Comment by uglyog** [comment]
Also, `pact_matching_ffi` supports setting up logging sinks (thanks to work from people from MITRE Corp). 

See https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching_ffi/examples/logging/src/main.c for an example.

**Comment by mefellows** [comment]
Ah yes. I think that's probably better.

Do you think it makes sense to move the `log()` function from #105 into that package so there is a single package to log? 

Would that even work, as they are separate libraries?

**Comment by uglyog** [comment]
We can move it, but that means the downstream implementations will need to link both libraries. Might be a better option to move it and then make `pact_mock_server_ffi` depend on `pact_matching_ffi`, that way all the FFI functions will be in a single shared lib. But then you can't link both, as you will get function name conflicts.

**Comment by mefellows** [comment]
Yeah I was wondering if you could re-expose them. Maybe need to think about namespacing the functions, is there a standard approach here?

**Comment by uglyog** [comment]
The logging FFI functions from `pact_matching_ffi` are now exposed in `pact_mock_server_ffi`.

**Comment by TimothyJones** [comment]
The standard approach for C is to prefix library functions - we could use
different prefixes for each pact lib?

**Comment by adamrodger** [comment]
This has since been implemented
