### ISSUE TITLE
Provider States URL Adds Extra /

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#110]
When you provide a provider states URL to the pact verifier, it appends an extra `/` to the `POST` URL if the user didn't supply one. 

This can make writing provider states endpoints tricky in some languages because the matching is different with and without the additional forward slash at the end. Instead, it should use the user-provided value as-is without modification in order to follow the principle of least surprise.

**Comment by mefellows** [comment]
Related aside, how do you do state handlers in the .NET interface? Ideally this endpoint is hidden from users for most cases and is mapped to a state handlers in the framework so users can just register native functions/classes (whatever is idiomatic)

**Comment by adamrodger** [comment]
The sample that's in PactNet at the moment uses some middleware to create the provider states endpoint, and then maps the provider state magic strings to various setup functions. The middleware could be disabled in config so it's not available on prod.

The sample needs migrating to ASP.Net Core but the principle would be the same I think.

I've also used quite a custom approach myself using PactNet in the past where we create stub versions of services that auto generate data instead of provider states, and also use conventional IDs (so calling GET /users/404 always returns a 404, PUT /orders/400 returns a 400 etc). I've found that's much easier to use than provider states personally and requires way less boilerplate setup code.

**Comment by mefellows** [comment]
> The sample that's in PactNet at the moment uses some middleware to create the provider states endpoint, and then maps the provider state magic strings to various setup functions. The middleware could be disabled in config so it's not available on prod.

Yep. I don't know .NET as well, but that was probably the number one biggest complaint I used to get in Pact JS (having to stand that server up). That, and people not understanding how promises worked....

> The sample needs migrating to ASP.Net Core but the principle would be the same I think.

It's probably worth starting without any additional features, but introducing the proxy middleware that I added to Pact Go/JS (and other languages have copied) generally made this problem much easier to deal with. It also very conveniently meant dealing with messages was trivial because it could follow a similar approach.

> I've also used quite a custom approach myself using PactNet in the past where we create stub versions of services that auto generate data instead of provider states, and also use conventional IDs (so calling GET /users/404 always returns a 404, PUT /orders/400 returns a 400 etc). I've found that's much easier to use than provider states personally and requires way less boilerplate setup code.

I've heard many a story like that. One wonders if we could somehow extract those patterns into the system somehow!

Anyway, I've hijacked this issue...

**Comment by mefellows** [comment]
FWIW e99307407c0c24314e73d125a5e1927252502a76 broke Pact Go. Minor fix, but pain to find.

The fix on my end was to not have a trailing `/` on the state path. 

With a trailing slash, it sends this odd request:
```
# Rust code
14:39:45 [DEBUG] (9) pact_verifier::provider_client: Sending Request ( method: POST, path: /, query: None, headers: Some({"Content-Type": ["application/json"]}), body: Present(72 bytes, application/json) ) to state change handler
# Go code
2021/07/04 00:37:24 [TRACE] message state handler &{Method:GET URL:/__setup/ Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] Referer:[http://localhost:64197/__setup]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:localhost:64197 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:[::1]:64200 RequestURI:/__setup/ TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000410480}
```

Without, it sends this:
```
# Rust code
14:37:43 [DEBUG] (9) pact_verifier::provider_client: Sending Request ( method: POST, path: /, query: None, headers: Some({"Content-Type": ["application/json"]}), body: Present(75 bytes, application/json) ) to state change handler

# Go handler...
2021/07/04 00:37:43 [TRACE] message state handler &{Method:POST URL:/__setup Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] Content-Length:[75] Content-Type:[application/json]] Body:0xc000410300 GetBody:<nil> ContentLength:75 TransferEncoding:[] Close:false Host:localhost:64209 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:[::1]:64212 RequestURI:/__setup TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000410340}
```

Also note the path seems incorrect, because that is not the path of the setup endpoint, but that is the case in both the working and failing request, so I assume it's logging incorrectly?

But the different verb is certainly what I'm seeing.
