### ISSUE TITLE
pact-consumer 0.7.6 compile is broken

### ISSUE THREAD

**Issue by audunhalland** [pact-foundation/pact-reference#126]
After updating dependencies with `cargo update`, `pact-consumer 0.7.6` fails to build. Transitive dependency to `pact_matching` has been bumped to `0.9.4`, and `pact-consumer` is incompatible with it. Lots of compile errors, the first one is:

```
   Compiling pact_consumer v0.7.6
error[E0432]: unresolved import `pact_matching::models::matchingrules::RuleLogic`
 --> /Users/audun/.cargo/registry/src/github.com-1ecc6299db9ec823/pact_consumer-0.7.6/src/patterns/special_rules.rs:3:80
  |
3 | use pact_matching::models::matchingrules::{MatchingRule, MatchingRuleCategory, RuleLogic};
  |                                                                                ^^^^^^^^^ no `RuleLogic` in `models::matchingrules`

```

**Comment by audunhalland** [comment]
I think semver has been violated somewhere in the inter-dependency of the various pact-reference crates. In the future, I think problems like this could be minimized if all crates are always released simultaneously. I know I have encountered similar problems before for `pact-consumer` (this crate _appears_ to be a bit less "prioritized" than the others)

**Comment by TimothyJones** [comment]
I don’t really have the context for the rust libs, but I think semver isn’t violated, because these are 0.x.x, which allows arbitrary breaking changes (this clearly isn’t ideal, as you point out)

@uglyog can we get a v1 release for the rust pieces so that we can communicate breaking changes clearer?

Also any way to orchestrate the builds / releases to reduce the risk of breaking changes is a win in my book.

**Comment by audunhalland** [comment]
For `0.x.y` packages, a changed `x` will denote a breaking change, at least in the Cargo interpretation of semver. `cargo update` will only bump to the latest `y` while keeping `x` the same. Cargo doc explains it better than me:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

**Comment by TimothyJones** [comment]
Oh, that's interesting! That's a widening of the [semver spec](https://semver.org/) which just says:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Looks like the Cargo docs mention this explicitly: 

> This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.

I hadn't noticed before that `^` `~` etc for selecting versions aren't part of the semver spec - meaning that they could potentially mean different things in (say) Cargo and npm. However, it looks like npm follows the same convention as cargo- see [here](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004).

Anyway, I'll stop hijacking this issue.

**Comment by uglyog** [comment]
Sorry about this, I haven't released the pact-consumer crate. I'm doing that now.

There has been a bit of churn while we're trying to get a good FFI interface. I don't think things will have to change much from here on, as we have moved all the FFI functions into a separate library and extracted all the models from the pact-matching one.

With hindsight, we should have bumped the minor versions of all the dependent crates, but it is now done and can't be changed.

**Comment by TimothyJones** [comment]
With pact-js we automate the version bumping from the commit history, which helps them be correct. It’s not a perfect solution, because you have to remember to mark breaking changes in the commit, but it does help reduce the risk. Would something like that help here?

**Comment by uglyog** [comment]
No, I don't think so. The minor versions had to be bumped.

**Comment by uglyog** [comment]
0.7.7 is released

**Comment by TimothyJones** [comment]
> The minor versions had to be bumped.

Yes, that's what I'm saying - we have tooling that reads the commit history and bumps the appropriate part of the version. It requires using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)), but then you can automate the process. 

On a release, all commits since the last release are read:

After 1.0.0,  If ​there's a commit that contains `BREAKING CHANGE` the major version, is bumped, otherwise if there's a commit that starts with `feat:` or `feat(whatever):` then the minor version is bumped, otherwise it's a patch version.

Before 1.0.0, I think the behaviour is `BREAKING CHANGE` is a minor bump as in the rust/npm docs, but I'm not sure (but since we are exposing this publicly, we should technically be at 1.0.0).

Look like this rust crate does a similar thing: https://crates.io/crates/convco

**Comment by TimothyJones** [comment]
This is the tool we use https://github.com/conventional-changelog/standard-version

It can be run with `npx standard-version`, and configured to bump files that aren't package.json, but you'd probably want something natively rust or at least rust toolchain aware.

**Comment by audunhalland** [comment]
0.7.7 works, thanks.
