### ISSUE TITLE
Rust: JSON post request results in Request-Mismatch with default values

### ISSUE THREAD

**Issue by joeftiger** [pact-foundation/pact-reference#282]
I am trying to use `pact-consumer` and setup a pact interaction with a `POST` request and JSON body.
However, I am constantly running into an error `500` with `"x-pact": "Request-Mismatch"`.

I broke it down to a simple example [on this repo](https://github.com/joeftiger/PactJson) and I do not see what I do wrong.

So far my guess is that using the following macro combination [on line 17](https://github.com/joeftiger/PactJson/blob/main/tests/pact_json.rs#L17-#L21) is at fault:
```rust
i.request
  .post()
  .path("/")
  .json_utf8()
  .json_body(json_pattern!(like!(json!(Data::default()))));
```
Though I tried various combinations and none seem to work. The aim is to allow any `POST` request with arbitrary `id` values (deserialized from the struct, however).

Am I overlooking something or is there a bug inside pact?

**Comment by mefellows** [comment]
It's because you called `json_utf8()` which changes the expected content type via `content-type` header to `application/json; charset=utf-8` but reqwest isn't sending it with the UTF charset parameter (just `application/json`). You just need `json_body(...)`, and removing the utf ones makes the test pass.

When I change the response line to:

```rust
.json_body(json_pattern!(like!(json!({}))));
```

The test errors as you would expect:

```
thread 'post_test' panicked at 'could not read response body: reqwest::Error { kind: Decode, source: Error("missing field `id`", line: 1, column: 2) }', tests/pact_json.rs:38:46
```

**Side note on Pact framework error messages**

I noticed that Pact wasn't printing the actual error message that would have made the underlying problem clear. The real error message is:

```
  - Mismatch with header 'content-type': Expected 'application/json' to match '^application/json; charset=(utf|UTF)-8$'
```

Which I think would have helped resolve the issue. I believe this error was being suppressed because of the other assertions before `

The error is only printed when (in this case) `pact` goes out of scope, however because there are other assertions before that happens I believe that suppresses the real problem - what's the best way to print errors in this case?

The [example](https://docs.rs/pact_consumer/latest/pact_consumer/#how-to-use-it) in the docs would suffer the exact same problem:

<img width="1048" alt="Screenshot 2023-06-03 at 9 14 36 am" src="https://github.com/pact-foundation/pact-reference/assets/53900/3842c569-958d-49a3-b9b1-64310431408f">

**Comment by rholshausen** [comment]
The mock server errors will now be written to standard error if the test is panicking because of another assertion that has failed. 
![image (2)](https://github.com/pact-foundation/pact-reference/assets/38309842/b6dadc7b-11fa-4097-b58b-844ca671e130)
